#server:
#  port: 8080  
spring:
  application:
    name: usuario-service      
  cloud:
    config:
      uri: http://localhost:8888/  
management:
  endpoints:
    web:
      exposure:
        include: "*"
#application-version: 1.0