server:
  port: 8080
  wait-time-in-ms-when-sync-empty: 3000
spring:
  profiles:
    nactive: native
  data:
    mongodb:
      uri: mongodb+srv://sam85avila:bRl4yO6pqQQlJOfW@cluster-samuel.gyzie4v.mongodb.net/?retryWrites=true&w=majority
#        host: ${MONGODB_URL}
      database: meme
      auto-index-creation: true
eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
application-version: 1.0
application:
  categoriaMemeService:
    url: http://categoria-meme-service:8080
    endpointConsultarCategoriaMeme: ${application.categoriaMemeService.url}/categoria
  usuarioService:
    url: http://usuario-service:8080
    endpointConsultarCliente: ${application.usuarioService.url}/usuario/isCadastrado/{id}