server:
  port: 8000
  wait-time-in-ms-when-sync-empty: 3000
spring:
  profiles:
    active: native
  data:
    mongodb:
      uri: mongodb://admin:backend@127.0.0.1:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: usuario
      auto-index-creation: true
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
application-version: 1.0