server:
  port: 8765
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: gateway-meme
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true